
GET http://localhost:8080/api/auth/token/expiration
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGVhciIsImlhdCI6MTc3NjQ0MDk0MCwiZXhwIjoxNzc2NTI3MzQwfQ.cYo8QhSZOPKnZ3GCdK5Qpmqgr0caZffvGT2Ft6iKOQY